// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCgYUvAuD7dSifMCxeHqo1Xm5no0pVUZ7M',
    appId: '1:364259914818:web:9a5c7ae932ccfc70aee9db',
    messagingSenderId: '364259914818',
    projectId: 'finalproject-90693',
    authDomain: 'finalproject-90693.firebaseapp.com',
    storageBucket: 'finalproject-90693.appspot.com',
    measurementId: 'G-G2LNB2DEJV',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBBOJ_CbEBuTPAvtF5S6fflBIqwLrSfS1Y',
    appId: '1:364259914818:android:9d73d04113b064acaee9db',
    messagingSenderId: '364259914818',
    projectId: 'finalproject-90693',
    storageBucket: 'finalproject-90693.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAVsjb7SZ5hAsj_HB1rRSHsoPlPH3h1KrM',
    appId: '1:364259914818:ios:a40686e06c1bd1e8aee9db',
    messagingSenderId: '364259914818',
    projectId: 'finalproject-90693',
    storageBucket: 'finalproject-90693.appspot.com',
    iosBundleId: 'com.example.dashboard',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAVsjb7SZ5hAsj_HB1rRSHsoPlPH3h1KrM',
    appId: '1:364259914818:ios:a40686e06c1bd1e8aee9db',
    messagingSenderId: '364259914818',
    projectId: 'finalproject-90693',
    storageBucket: 'finalproject-90693.appspot.com',
    iosBundleId: 'com.example.dashboard',
  );
}
